steps:
  - block: ":warning: Block step"
  - input: "What's your name?"
    fields:
      - text: "Your name"
        key: "name"
      - select: "Repetitions"
        key: "loops"
        options:
          - label: "1"
            value: "1"
          - label: "2"
            value: "2"
          - label: "3"
            value: "3"
          - label: "4"
            value: "4"
  - command: ".buildkite/group.sh | buildkite-agent pipeline upload"
  
    
